name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gabrielfalcao/pyenv-action@v18
        with:
          default: 3.12
      - name: Build
        shell: bash
        run: cargo build --verbose
      - name: Run tests
        shell: bash
        run: cargo test --verbose
  clippy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  
    steps:
      - uses: actions/checkout@v4
      - uses: gabrielfalcao/pyenv-action@v18
        with:
          default: 3.12
      - name: Build
        shell: bash
        run: cargo build --verbose
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
      - name: Run clippy with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo clippy --message-format=json | reviewdog -f=clippy -reporter=github-pr-check

